2018-07-06 14:04:24.635 [error] <0.307.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.312.0> exit with reason normal in context child_terminated
2018-07-06 14:05:59.827 [error] <0.299.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.304.0> exit with reason normal in context child_terminated
2018-07-06 14:05:59.912 [error] <0.375.0>@Elixir.Plug.Adapters.Cowboy2:child_spec CRASH REPORT Process <0.375.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Plug.Adapters.Cowboy2':child_spec(http, 'Elixir.AgalaWebhooksExamples.Router', [], [{port,8080}]) in application_master:init/4 line 134
2018-07-06 14:07:26.425 [error] <0.260.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.265.0> exit with reason normal in context child_terminated
2018-07-06 14:09:22.839 [error] <0.259.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.264.0> exit with reason normal in context child_terminated
2018-07-06 14:12:03.319 [error] <0.278.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.283.0> exit with reason normal in context child_terminated
2018-07-06 19:07:25.128 [error] <0.542.0> CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 4,clauses => nil,function => do_match,kind => nil,module => 'Elixir.Awe.Router'},[{'Elixir.Awe.Router',do_match,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"br...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:07:25.183 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.541.0>,1,<0.542.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 4,clauses => nil,function => do_match,kind => nil,module => 'Elixir.Awe.Router'},[{'Elixir.Awe.Router',do_match,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtm...">>,...},...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:07:26.183 [error] <0.545.0> CRASH REPORT Process <0.545.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 4,clauses => nil,function => do_match,kind => nil,module => 'Elixir.Awe.Router'},[{'Elixir.Awe.Router',do_match,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"br, gzip, deflate">>,<<"accept-language">> => <<"en-us">>,<<"...">> => ...,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:07:26.184 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.544.0>,1,<0.545.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 4,clauses => nil,function => do_match,kind => nil,module => 'Elixir.Awe.Router'},[{'Elixir.Awe.Router',do_match,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encod...">> => ...,...},...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:11:16.456 [error] <0.555.0> CRASH REPORT Process <0.555.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:11:16.457 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.554.0>,1,<0.555.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:11:16.646 [error] <0.558.0> CRASH REPORT Process <0.558.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 230,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:11:16.648 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.557.0>,1,<0.558.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 230,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:11:16.881 [error] <0.561.0> CRASH REPORT Process <0.561.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:11:16.883 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.560.0>,1,<0.561.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:11:17.340 [error] <0.564.0> CRASH REPORT Process <0.564.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:11:17.342 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.563.0>,1,<0.564.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:11:18.021 [error] <0.567.0> CRASH REPORT Process <0.567.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:11:18.023 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.566.0>,1,<0.567.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:11:19.145 [error] <0.570.0> CRASH REPORT Process <0.570.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:11:19.146 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.569.0>,1,<0.570.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:11:22.627 [error] <0.573.0> CRASH REPORT Process <0.573.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:11:22.629 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.572.0>,1,<0.573.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:11:40.751 [error] <0.576.0> CRASH REPORT Process <0.576.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:11:40.753 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.575.0>,1,<0.576.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:13:01.687 [error] <0.631.0> CRASH REPORT Process <0.631.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:13:01.687 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.630.0>,1,<0.631.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:13:46.092 [error] <0.634.0> CRASH REPORT Process <0.634.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 140,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"connection">> => <<"close">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:13:46.095 [error] <0.330.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.633.0>,1,<0.634.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 140,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:14:09.506 [error] <0.286.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.291.0> exit with reason normal in context child_terminated
2018-07-06 19:14:17.181 [error] <0.472.0> CRASH REPORT Process <0.472.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"de...">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:14:17.236 [error] <0.338.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.471.0>,1,<0.472.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 321,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:14:21.625 [error] <0.475.0> CRASH REPORT Process <0.475.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 140,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"connection">> => <<"close">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:14:21.632 [error] <0.338.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.474.0>,1,<0.475.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 140,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:14:28.462 [error] <0.478.0> CRASH REPORT Process <0.478.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 140,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"connection">> => <<"close">>,...},...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:14:28.464 [error] <0.338.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.477.0>,1,<0.478.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,exports => nil,function => fetch,module => 'Elixir.Plug.Conn',reason => <<"Plug.Conn does not implement the Access behaviour">>},[{'Elixir.Plug.Conn',fetch,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 140,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:14:59.464 [error] <0.273.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.278.0> exit with reason normal in context child_terminated
2018-07-06 19:16:23.537 [error] <0.251.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.256.0> exit with reason normal in context child_terminated
2018-07-06 19:16:48.988 [error] <0.440.0> CRASH REPORT Process <0.440.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 4,clauses => nil,function => do_match,kind => nil,module => 'Elixir.Awe.Router'},[{'Elixir.Awe.Router',do_match,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"host">> => <<"localhost:8080">>,<<"user-agent">> => <<"curl/7.54.0">>},host => <<"localh...">>,...}},...},...],...},...]},...} in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20 in 'Elixir.Plug.Adapters.Cowboy2.Handler':init/2 line 20
2018-07-06 19:16:49.031 [error] <0.303.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.Awe.Router.HTTP',<0.439.0>,1,<0.440.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 4,clauses => nil,function => do_match,kind => nil,module => 'Elixir.Awe.Router'},[{'Elixir.Awe.Router',do_match,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy2.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"host">> => <<"lo...">>,...},...}},...},...],...},...]},...},...]},...}}
2018-07-06 19:19:21.846 [error] <0.251.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.256.0> exit with reason normal in context child_terminated
2018-07-06 19:20:28.845 [error] <0.251.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.256.0> exit with reason normal in context child_terminated
2018-07-06 19:21:07.449 [error] <0.299.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.304.0> exit with reason normal in context child_terminated
